// @generated by protobuf-ts 2.9.7-alpha.5 with parameter only_http
// @generated from protobuf file "Rum" (syntax proto2)
// tslint:disable
import { Rum1Client$1 } from "./service1.client";
import { RumClient$1 } from "./service.client";
import type { VAxiosInstance } from "@protobuf-ts/runtime-http";
import type { VAxios } from "@protobuf-ts/runtime-http";
import type { HttpOptions } from "@protobuf-ts/runtime-http";
export class HttpClient {
    rum: RumClient$1;
    rum1: Rum1Client$1;
    constructor(vAxios: VAxios | VAxiosInstance, opt: HttpOptions = {}) {
        this.rum = new RumClient$1(vAxios, opt);
        this.rum1 = new Rum1Client$1(vAxios, opt);
    }
}
