// @generated by protobuf-ts 2.9.8 with parameter only_http,long_type_number
// @generated from protobuf file "message.proto" (package "rum", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf message rum.ReportReply
 */
export interface ReportReply {
}
/**
 * @generated from protobuf message rum.ReportRequest
 */
export interface ReportRequest {
    /**
     * sdk版本
     *
     * @generated from protobuf field: string sdk_ver = 1;
     */
    sdkVer: string;
    /**
     * sdk名称
     *
     * @generated from protobuf field: string sdk_name = 2;
     */
    sdkName: string;
    /**
     * 上报id
     *
     * @generated from protobuf field: string id = 3;
     */
    id: string;
    /**
     * 应用id
     *
     * @generated from protobuf field: string app_id = 4;
     */
    appId: string;
    /**
     * 用户id
     *
     * @generated from protobuf field: string user_id = 5;
     */
    userId: string;
    /**
     * 应用名称
     *
     * @generated from protobuf field: string app_name = 6;
     */
    appName: string;
    /**
     * @generated from protobuf field: repeated rum.ReportRequest.Data data = 7;
     */
    data: ReportRequest_Data[];
}
/**
 * @generated from protobuf message rum.ReportRequest.Data
 */
export interface ReportRequest_Data {
    /**
     * 分类
     *
     * @generated from protobuf field: rum.Category category = 1;
     */
    category: Category;
    /**
     * 子分类
     *
     * @generated from protobuf field: rum.SubCategory sub_category = 2;
     */
    subCategory: SubCategory;
    /**
     * 页面地址
     *
     * @generated from protobuf field: string page_url = 3;
     */
    pageUrl: string;
    /**
     * 指标获取时间，ms级时间戳
     *
     * @generated from protobuf field: uint32 time = 4;
     */
    time: number;
    /**
     * 性能数据
     *
     * @generated from protobuf field: optional rum.ReportRequest.Data.Performance performance = 5;
     */
    performance?: ReportRequest_Data_Performance;
}
/**
 * @generated from protobuf message rum.ReportRequest.Data.Performance
 */
export interface ReportRequest_Data_Performance {
    /**
     * 开始时间: 如：400，单位ms
     *
     * @generated from protobuf field: optional double start_time = 1;
     */
    startTime?: number;
    /**
     * 渲染时间: 如 400
     *
     * @generated from protobuf field: optional double render_time = 2;
     */
    renderTime?: number;
    /**
     * dom解析耗时
     *
     * @generated from protobuf field: optional double dom_parse = 15;
     */
    domParse?: number;
    /**
     * 资源加载耗时
     *
     * @generated from protobuf field: optional double res = 16;
     */
    res?: number;
}
/**
 * @generated from protobuf enum rum.Category
 */
export enum Category {
    /**
     * 未知
     *
     * @generated from protobuf enum value: Category_Unknown = 0;
     */
    Category_Unknown = 0,
    /**
     * 性能
     *
     * @generated from protobuf enum value: Category_Performance = 1;
     */
    Category_Performance = 1,
    /**
     * 错误
     *
     * @generated from protobuf enum value: Category_Error = 2;
     */
    Category_Error = 2,
    /**
     * 行为
     *
     * @generated from protobuf enum value: Category_Behaviour = 3;
     */
    Category_Behaviour = 3,
    /**
     *
     *
     * @generated from protobuf enum value: Category_Custom = 4;
     */
    Category_Custom = 4
}
/**
 * @generated from protobuf enum rum.SubCategory
 */
export enum SubCategory {
    /**
     * 未知
     *
     * @generated from protobuf enum value: Subtype_Known = 0;
     */
    Subtype_Known = 0,
    /**
     * 白屏时间/首次绘制
     *
     * @generated from protobuf enum value: FirstPaint = 1;
     */
    FirstPaint = 1,
    /**
     * 首屏时间/首次内容绘制
     *
     * @generated from protobuf enum value: FirstContentulPaint = 2;
     */
    FirstContentulPaint = 2,
    /**
     * 最大内容绘制
     *
     * @generated from protobuf enum value: LargestContentfulPaint = 3;
     */
    LargestContentfulPaint = 3
}
