// @generated by protobuf-ts 2.9.7-alpha.0 with parameter only_http
// @generated from protobuf file "service.proto" (package "rum", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-http";
/**
 * @generated ServiceType for protobuf service rum.Rum
 */
export const Rum = new ServiceType("rum.Rum", [
    { name: "Report", options: { "google.api.http": { post: "/v1/rum/report", body: "*" } }, I: { typeName: "ReportRequest" }, O: { typeName: "ReportRequest" } },
    { name: "transforming", options: { "google.api.http": { get: "/v1/rum/transforming" } }, I: { typeName: "ReportRequest" }, O: { typeName: "ReportRequest" } }
]);
