// @generated by protobuf-ts 2.9.5 with parameter only_http
// @generated from protobuf file "service.proto" (package "rum", syntax proto3)
// tslint:disable
import { ReportReply } from "./message";
import { ReportRequest } from "./message";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service rum.Rum
 */
export const Rum = new ServiceType("rum.Rum", [
    { name: "Report", options: { "google.api.http": { post: "/v1/rum/report", body: "*" } }, I: ReportRequest, O: ReportReply },
    { name: "transforming", options: { "google.api.http": { get: "/v1/rum/transforming" } }, I: ReportRequest, O: ReportReply }
]);
