// @generated by protobuf-ts 2.9.7-alpha.5 with parameter only_http
// @generated from protobuf file "service1.proto" (package "rum", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-http";
/**
 * @generated ServiceType for protobuf service rum.Rum1
 */
export const Rum1 = new ServiceType("rum.Rum1", [
    { name: "ReportAbc", options: { "google.api.http": { post: "/v1/rum/report", body: "*" } }, I: { typeName: "ReportRequest" }, O: { typeName: "ReportRequest" } },
    { name: "transforming", options: { "google.api.http": { post: "/v1/rum/transforming", body: "file" } }, I: { typeName: "ReportRequest" }, O: { typeName: "ReportRequest" } }
]);
