// @generated by protobuf-ts 2.9.8 with parameter only_http,long_type_number
// @generated from protobuf file "service.proto" (package "rum", syntax proto3)
// tslint:disable
import type { VAxiosInstance } from "@protobuf-ts/runtime-http";
import type { VAxios } from "@protobuf-ts/runtime-http";
import { HttpTransport } from "@protobuf-ts/runtime-http";
import type { ServiceInfo } from "@protobuf-ts/runtime-http";
import { Rum } from "./service";
import type { UploadFile } from "@protobuf-ts/runtime-http";
import type { ReportReply } from "./message";
import type { ReportRequest } from "./message";
import type { HttpResult } from "@protobuf-ts/runtime-http";
import type { HttpOptions } from "@protobuf-ts/runtime-http";
/**
 * @generated from protobuf service rum.Rum
 */
export interface IRumClient$1 {
    /**
     * 上报接口
     *
     * @generated from protobuf rpc: Report(rum.ReportRequest) returns (rum.ReportReply);
     */
    report(input: ReportRequest, options?: HttpOptions["requestOptions"]): HttpResult<ReportReply>;
    /**
     * 上传接口
     *
     * @generated from protobuf rpc: transforming(rum.ReportRequest) returns (rum.ReportReply);
     */
    transforming(input: UploadFile, options?: HttpOptions["requestOptions"]): HttpResult<ReportReply>;
}
/**
 * @generated from protobuf service rum.Rum
 */
export class RumClient$1 implements IRumClient$1, ServiceInfo {
    methods = Rum.methods;
    public defHttp: HttpTransport;
    constructor(vAxios: VAxios | VAxiosInstance, opt: HttpOptions = {}) {
        this.defHttp = new HttpTransport(vAxios, opt);
        this.report = this.report.bind(this);
        this.transforming = this.transforming.bind(this);
    }
    /**
     * 上报接口
     *
     * @generated from protobuf rpc: Report(rum.ReportRequest) returns (rum.ReportReply);
     */
    report(input: ReportRequest, options?: HttpOptions["requestOptions"]): HttpResult<ReportReply> {
        const method = this.methods[0], opt = options;
        return this.defHttp.request<ReportRequest, ReportReply>(method, input, opt);
    }
    /**
     * 上传接口
     *
     * @generated from protobuf rpc: transforming(rum.ReportRequest) returns (rum.ReportReply);
     */
    transforming(input: UploadFile, options?: HttpOptions["requestOptions"]): HttpResult<ReportReply> {
        const method = this.methods[1], opt = options;
        return this.defHttp.request<UploadFile, ReportReply>(method, input, opt);
    }
}
